# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6ddf5f08629bbae4c6ee105aaa2c6ec898096a86da8edb76854ccd01135fc7ebb89594fba4b8f6a93a624d94df35751a0aa82b33c6fbd7db9fa25db12beb5ab

test:
  secret_key_base: 07c1dffdf31b4a1681a93ed2ebaa4796d7079e57bdd2ff32aa40b231ef2822a411e2b2f38e8e376d52a229b62249019a70e9212c1355f8ea26c0ccfb1f48715f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
